---
title: 第十一章 期约（Promise）与异步（async）函数
date: 2020-12-23
categories:
 - 读书
tags:
 - javascript高级程序设计
#  - js
---

## async函数

### 返回值
异步函数的返回值会被`Promise.resolve()`包装成一个`Promise`对象。在函数外部调用这个函数可以得到它返回的`Promise`：

```javascript
async function foo(){
    console.log(1);
    return 3
}

foo().then(console.log);
console.log(2)
// 1
// 2
// 3
```

当然，直接返回一个Promise对象也是一样的。

### Promise.reject()

在函数中单独使用`Promise.reject()`不会被异步函数捕获

```javascript
async function foo(){
    console.log(1);
    Promise.reject(3)
}

foo().catch(console.log);
console.log(2)
// 1
// 2
// Uncaught (in promise):3
```

如前面的例子所示，单独的`Promise.reject()`不会被异步函数捕获，而会抛出未捕获错误。不过，如果使用`await`关键字来接收，则可以被捕获（返回）：

```javascript
async function foo(){
    console.log(1);
    await Promise.reject(3)
    console.log(4) // 这行代码不会执行
}

foo().catch(console.log);
console.log(2)
// 1
// 2
// 3
```

## 实现sleep()

```javascript
async function sleep(delay){
    return new Promise(resolve=>setTimeout(resolve,delay))
}

async function foo(){
    const t0=Date.now();
    await sleep(1500);
    console.log(Date.now()-t0)
}

foo(); // 1502
```